<?php

namespace AppBundle\Repository;

/**
 * Creneau_programmeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Creneau_programmeRepository extends \Doctrine\ORM\EntityRepository
{

}
