<?php

namespace AppBundle\Repository;

/**
 * GrillesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrillesRepository extends \Doctrine\ORM\EntityRepository
{
}
